service:
  name: serverless-nest-template

useDotenv: true

plugins:
  # - '@hewmen/serverless-plugin-typescript'
  # - serverless-plugin-optimize
  - serverless-offline
  # - serverless-plugin-warmup

# custom:
#   # Enable warmup on all functions (only for production and staging)
#   warmup:
#       - production
#       - staging

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, env:AWS_REGION}
  stage: ${opt:stage, 'local'}
  profile: dev-sls-profile
  # deploymentBucket:
  #   name: ${env:SLS_DEPLOYMENT_BUCKET}
  #   blockPublicAccess: true
  # endpointType: private
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: ${env:LAMBDA_AWS_NODEJS_CONNECTION_REUSE_ENABLED, '1'}

package:
  # individually: true
  include:
    - dist/**.js
  exclude:
    - ./**.md
    - ./**.env*
    - ./tsconfig*.json
    - coverage/**
    - nest-cli.json
    - src/**
    - docker/**
    - docs/**
    - test/**

functions:
  main:
    handler: dist/index.handler
    # environment:
    #   S3_EXPORT_BUCKET_NAME: ${cf:${self:custom.infraStack}.exportBucketName}
    #   SSM_DATABASE_USER_SECRET_ID: ${env:SSM_DATABASE_USER_SECRET_ID}
    events:
      - http:
          cors: true
          path: '/'
          method: GET
      # - http:
      #     cors: true
      #     path: '{proxy+}'
      #     method: any
